# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables: 
  tag: '$(Build.BuildId)'
  dockerImageName: '$(System.CollectionUri)/$(System.TeamProject)'
  

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: 'Default'
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        buildContext: $(Build.SourcesDirectory)
        dockerfile: '$(Build.SourcesDirectory)/PlaningPoker.Web/Dockerfile'
        arguments: -t $(dockerImageName):$(tag)
        tags: |
          $(tag)
    - task: CmdLine@2
      displayName: 'Save Docker image'
      inputs:
        script: 'docker image save planingpoker:$(tag) -o $(Build.ArtifactStagingDirectory)/$(System.TeamProject).tar'
        failOnStderr: true
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        publishLocation: 'pipeline'
    
